baseurl: /starter
permalink: pretty
title: Wikimedia Strategy
markdown: kramdown
tags:
- home
- about
- resources
include: ["_pages"]
plugins:
  - jekyll-redirect-from
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
prose:
  rooturl: '_pages'
  siteurl: 'http://j4n-co.github.io/starter/'
  relativeLinks: 'http://j4n-co.github.io/starter/links.jsonp'
  media: 'media'
  metadata:
    _pages:
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "tags"
        field:
          element: "text"
          label: "tag"
          value: ""