baseurl: /starter
permalink: pretty
markdown: rdiscount
title: Wikimedia Strategy
tags:
- home
- about
- resources
plugins:
  - jekyll-redirect-from
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
prose:
  rooturl: '_posts'
  siteurl: 'http://j4n-co.github.io/starter/'
  relativeLinks: 'http://j4n-co.github.io/starter/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "tags"
        field:
          element: "text"
          label: "tag"
          value: ""